# -*- coding: utf-8 -*-
"""Planet AI for Personal Assistance

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YWzIVE2a_KpkdzAupL1_EW0n2FQPXoyc

Step to Follow  :

1. Get Input text / questions from user.
2. Based on que what to do?
    . On device operation
    . Who are you kind of msgs
    . asking the assistant some ques
3. Give proper ans to each que.
4. If que is related to serach internet,get the ans from google gemini model.
5. If you got an ans then please convert it to Text to Speech(GTTS).

```
# This is formatted as code
```
"""

#Text to Speech converter library
!pip install gTTS

pip install -q -U google-generativeai

import pathlib
import textwrap
from gtts import gTTS

import google.generativeai as genai   #API

from IPython.display import display
from IPython.display import Markdown

from IPython.display import Audio, display       #audio library


def to_markdown(text):
  text = text.replace('•', '  *')
  return Markdown(textwrap.indent(text, '> ', predicate=lambda _: True))

GOOGLE_API_KEY = "AIzaSyCTgivQiqEbBrXxQF1hO9894rwSvFn_z8E"
genai.configure(api_key=GOOGLE_API_KEY)

def ask_que(name):
   ques = 'Hey ' + name + ' , How can i help you ? '
   ques = input(ques)
   return ques

ask_que("esh")

import spacy
def classify_ques(question):
  goahead_with_websearch = False
  device_lst = ["alarm","reminder","message","Video call","call","text","SMS","chat"]
  #List created for the inputs received from the devices.
  personal_lst = ["Who are you?","who created you"]

  device = False
  for i in device_lst:
    if i in question:
      device = True

  if device:
    print("This question is not relatable to Device things, not Supported by us.")

  personal_question = False
  for i in personal_lst:
    if i in question.lower():
       personal_question = True

  if personal_question:
     print("Hey I'm a personal Virtual Assistant created by Eshwari Chavan")

  if device:
    goahead_with_websearch = False
  elif personal_question:
    goahead_with_websearch = False
  else:
    goahead_with_websearch = True

  return goahead_with_websearch

classify_ques("Who are you?")

#Start Searching with Google gemini ,using Gemini APIs to do the work
#step1: Go to https://ai.google.dev/ then create a API import it grant the access and copy the code.
from google.colab import userdata
GOOGLE_API_KEY = userdata.get("GOOGLE_API_KEY")
model = genai.GenerativeModel('gemini-pro')

response = model.generate_content("What is the meaning of google API ?")
response.text
to_markdown(response.text)

def ask_gemini(ques):
  modified_prompt = ' Hey give me answer to this question ' + ques + ' in maximum of 20 words '
  response = model.generate_content(ques)
  to_markdown(response.text)
  return response.text

def speak(answer):
  tts = gTTS(answer)
  tts.save('audio.mp3')
  display(Audio('audio.mp3', autoplay=True))

speak("i hope this will work well ")

have_any_other_ques = 'y'
name = ''

while have_any_other_ques == 'y':

  if name == '':
    name = input("Hey What is your Name ?")

  q = ask_que(name)
  go_ahead = classify_ques(q)
  answer = ''

  if go_ahead == True:
    answer = ask_gemini(q)
    speak(answer)
    print(answer)

  have_any_other_ques = input("Do you have any other questions ??")